<?php $_code = $this->getMethodCode(); ?>
<?php $media_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none">
    <li>
        <div style="float:right;"><img src="<?php echo $media_url; ?>micropayment/logo_small.png" /></div>
        <div>

            <?php switch($_code) {
                case 'mcpprepay':
                    echo Mage::helper('mcpservice')->__('description_prepay');
                break;
                case 'mcpebank2pay':
                    echo Mage::helper('mcpservice')->__('description_sofort');
                break;
                case 'mcpcreditcard':
                    echo Mage::helper('mcpservice')->__('description_creditcard');
                break;
                case 'mcpdebit':
                    echo Mage::helper('mcpservice')->__('description_debit');
                break;
            }
            ?>
        </div>
        <div style="clear:both;"></div>
    </li>
</ul>

